(import chicken.io chicken.process-context chicken.tcp)
(let ((args (command-line-arguments)))
  (if (= (length args) 3)
      (let ((hostname (list-ref args 0))
            (username (list-ref args 1))
            (password (list-ref args 2)))
        (let-values (((in out) (tcp-connect hostname 4242)))
          (let ((line (string-append "register " username "\t" password)))
            (write-line line out)
            (print (read-line in))
            (close-input-port in)
            (close-output-port out))))
      (print "Usage: " (program-name) " HOSTNAME USERNAME PASSWORD")))
